### ISSUE TITLE
Generated file names are not correct

### ISSUE THREAD

**Issue by duchuy** [paazmaya/gulp-sakugawa#11]
Hi, 
I'm using gulp-sakugawa 0.4.0

I followed the sample syntax 

gulp.task('default', function() {
  gulp.src('pure-min.css')
    .pipe(gulpSakugawa({
      maxSelectors: 400,
      mediaQueries: 'separate',
      suffix: '_'
    }))
    .pipe(gulp.dest('.'));
});

the files generated are:
pure-min.css_1.css
pure-min.css_2.css

instead of pure-min_1.css and pure-min_2.css 
If I run from command line directly:
C:/>sakugawa pure-min.css
The files generated are correct: pure-min_1.css and pure-min_2.css 

Thanks.
Alan

**Comment by duchuy** [comment]
I created pull request here

https://github.com/duchuy/gulp-sakugawa

**Comment by paazmaya** [comment]
Perhaps the issue has been fixed via #10 ?

**Comment by duchuy** [comment]
hi. thanks. yes it has been fixed via #10 
i am using npm package.json with "gulp-sakugawa": "^0.4.0"
and I think that version does not have the fix yet.

2nd issue, our system requires the HTML to only contain 1 css file: styles.css (generated via SASS)
so we do not want to change the HTML to include styles_01.css, styles_02.css, etc.
This is also the case when the CSS base grows to have styles_03.css generated, we will need to update back all existing pages. (this can be done easily via update header.html, but we will need to update all existing compiled HTML pages into GIT/SVN).

So I'd to propose another flag addImport. if addImport = true,
styles.css will be changed to include:
@import styles_01.css
@import styles_02.css

if addImport = false (default), styles.css content will remain the same.
Thanks. Alan

**Comment by paazmaya** [comment]
@duchuy can you please open a new issue with your feature request and provide clear examples what happens in different situations?
I think it should be done for `sakugawa` which is the module used by this `gulp-sakugawa`, https://github.com/paazmaya/sakugawa
