### ISSUE TITLE
Split files are unminified

### ISSUE THREAD

**Issue by fraincs** [paazmaya/gulp-sakugawa#16]
Maybe it's an error in my gulp setup but I pass a minified css file and the result is two unminified files

**Comment by paazmaya** [comment]
Format is not preserved, hence not minified...
Perhaps, if you wish it to be preserved, open a PR in https://github.com/paazmaya/sakugawa

**Comment by paazmaya** [comment]
Closing as "won't fix" for now, as it is not an intended feature.
In case format preservation is wanted, then it should be done in `sakugawa` package.
